[build]
publish = "dist"
functions = "netlify/functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

# Redirect API requests to the Express function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200

# Serve React app properly (for React Router support)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

